name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Godot
        uses: firebelley/setup-godot@v2
        with:
          godot-version: '4.2.1'
          export-templates: true

      - name: Export Android
        run: |
          mkdir -p build
          godot --headless --export-release "Android" build/Voyager-19.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Voyager-19-APK
          path: build/Voyager-19.apk
          
